version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production

  hashcat:
    image: hashcat/hashcat
    entrypoint: ["hashcat", '-m', '1000', '-O', '-a3', '-i', 'hash.txt']  # Substitua com o comando real para rodar o Hashcat
    volumes:
      - ./data:/data
