version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - .:/app  # Assegure que o caminho esteja correto
    environment:
      - FLASK_ENV=production

  hashcat:
    image: hashcat/hashcat
    entrypoint: ["hashcat", "--version"]  # Substitua com o comando desejado
    volumes:
      - ./data:/data
