version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  hashcat:
    build:
      context: .
      dockerfile: Dockerfile.hashcat  # Nome do Dockerfile específico para o Hashcat
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
