version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  hashcat:
    image: hashcat/hashcat
    entrypoint: ["hashcat", "--version"]
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
