version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'

  hashcat:
    image: hashcat/hashcat
    entrypoint: ["hashcat", '-m', '1000', '-O', '-a3', '-i', 'hash.txt']  # Modifique conforme necessário para rodar Hashcat
    volumes:
      - ./data:/data
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
